# Generated by Django 4.0.2 on 2022-02-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('title', 'price')},
        ),
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.URLField(verbose_name='Link to Image'),
        ),
    ]
