# Generated by Django 4.0.2 on 2022-02-27 09:28

import django.core.validators
from django.db import migrations, models
import music_app.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(2), music_app.web.validators.validate_letters]),
        ),
    ]
