# Generated by Django 4.0.2 on 2022-02-27 09:37

import django.core.validators
from django.db import migrations, models
import music_app.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), music_app.web.validators.validate_letters]),
        ),
    ]
